spring:
  admin:
    username: ${ADMIN_USERNAME:root}
    password: ${ADMIN_PASSWORD:root}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/migrations/db.changelog-master.yaml

server:
  port: 8080

hmac:
  key: ${HMAC_KEY:6B3f4pJZ1aY8fR4+zTqJY1C0JQ8Fn+2kjkFq8R9bN7g=}
jwt:
  access:
    secret: ${JWT_ACCESS_SECRET:fe36efc1dc7ed4e847bba155b7932318f2729c68428c891f90de21849851aa4a}
    expiration: ${JWT_ACCESS_EXPIRATION:600000}
  refresh:
    secret: ${JWT_REFRESH_SECRET:fe36efc1dc7ed4e847bba155b7932318f2729c68428c891f90de21849851aa4a}
    expiration: ${JWT_REFRESH_EXPIRATION:604800000}
